#!/usr/bin/env python3
"""PM CONTROL TOWER - Platform Overview (executive demo handout).
Body PDF via ReportLab (SimpleDocTemplate, no TOC) -> merged with HTML/Playwright cover.
Palette: cascade cold-intent minimal (steel navy family) - values from design_engine.py output.
"""
import os
import sys

PDF_SKILL_DIR = "/home/z/my-project/skills/pdf"
_scripts = os.path.join(PDF_SKILL_DIR, "scripts")
if _scripts not in sys.path:
    sys.path.insert(0, _scripts)

from reportlab.lib import colors
from reportlab.lib.enums import TA_JUSTIFY, TA_LEFT, TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import inch
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (
    CondPageBreak, HRFlowable, KeepTogether, Paragraph,
    SimpleDocTemplate, Spacer, Table, TableStyle,
)

# ---------- Fonts (allowed set only) ----------
FONT_DIR = "/usr/share/fonts"
pdfmetrics.registerFont(TTFont("NotoSerifSC", f"{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf"))
pdfmetrics.registerFont(TTFont("NotoSerifSC-Bold", f"{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf"))
try:
    _sans_sc = f"{FONT_DIR}/truetype/chinese/NotoSansSC-Regular.ttf"
    if not os.path.exists(_sans_sc):
        _sans_sc = f"{FONT_DIR}/truetype/chinese/NotoSansSC[wght].ttf"  # variable font fallback
    pdfmetrics.registerFont(TTFont("Noto Sans SC", _sans_sc))
    pdfmetrics.registerFont(TTFont("Noto Sans SC Bold", _sans_sc))
    registerFontFamily("Noto Sans SC", normal="Noto Sans SC", bold="Noto Sans SC Bold")
except Exception:
    pass  # optional secondary fallback — chain skips unregistered fonts safely
pdfmetrics.registerFont(TTFont("FreeSerif", f"{FONT_DIR}/truetype/freefont/FreeSerif.ttf"))
pdfmetrics.registerFont(TTFont("FreeSerif-Bold", f"{FONT_DIR}/truetype/freefont/FreeSerifBold.ttf"))
pdfmetrics.registerFont(TTFont("FreeSerif-Italic", f"{FONT_DIR}/truetype/freefont/FreeSerifItalic.ttf"))
pdfmetrics.registerFont(TTFont("FreeSerif-BoldItalic", f"{FONT_DIR}/truetype/freefont/FreeSerifBoldItalic.ttf"))
pdfmetrics.registerFont(TTFont("DejaVuSans", f"{FONT_DIR}/truetype/dejavu/DejaVuSansMono.ttf"))
registerFontFamily("NotoSerifSC", normal="NotoSerifSC", bold="NotoSerifSC-Bold")
registerFontFamily("Noto Sans SC", normal="Noto Sans SC", bold="Noto Sans SC Bold")
registerFontFamily("FreeSerif", normal="FreeSerif", bold="FreeSerif-Bold",
                   italic="FreeSerif-Italic", boldItalic="FreeSerif-BoldItalic")
registerFontFamily("DejaVuSans", normal="DejaVuSans", bold="DejaVuSans")

from pdf import install_font_fallback  # noqa: E402
install_font_fallback()

# ---------- Cascade Palette (auto-generated by design_engine.py palette-cascade, cold/minimal) ----------
PAGE_BG       = colors.HexColor('#f6f6f7')
SECTION_BG    = colors.HexColor('#edeeef')
CARD_BG       = colors.HexColor('#ebedee')
TABLE_STRIPE  = colors.HexColor('#f0f2f2')
HEADER_FILL   = colors.HexColor('#32454e')
COVER_BLOCK   = colors.HexColor('#445e6b')
BORDER        = colors.HexColor('#b5c4cc')
ICON          = colors.HexColor('#3d6b82')
ACCENT        = colors.HexColor('#3396c8')
ACCENT_2      = colors.HexColor('#c74b60')
TEXT_PRIMARY  = colors.HexColor('#1f2223')
TEXT_MUTED    = colors.HexColor('#7e8588')

TABLE_HEADER_COLOR = HEADER_FILL
TABLE_HEADER_TEXT  = colors.white
TABLE_ROW_EVEN     = colors.white
TABLE_ROW_ODD      = TABLE_STRIPE

# ---------- Document geometry ----------
MARGIN = 0.95 * inch
PAGE_W, PAGE_H = A4
AVAIL_W = PAGE_W - 2 * MARGIN
AVAIL_H = PAGE_H - 2 * MARGIN
H1_ORPHAN = AVAIL_H * 0.25
MAX_KEEP_HEIGHT = PAGE_H * 0.4

OUT = "/home/z/my-project/scripts/overview-body.pdf"
DOC_TITLE = "PM Control Tower - Platform Overview"

# ---------- Styles ----------
h1_style = ParagraphStyle(
    "H1", fontName="FreeSerif", fontSize=20, leading=25,
    textColor=HEADER_FILL, spaceBefore=0, spaceAfter=4)
body_style = ParagraphStyle(
    "Body", fontName="FreeSerif", fontSize=10.5, leading=17,
    alignment=TA_JUSTIFY, textColor=TEXT_PRIMARY, spaceBefore=0, spaceAfter=10)
bullet_style = ParagraphStyle(
    "Bullet", fontName="FreeSerif", fontSize=10.5, leading=16.5,
    alignment=TA_LEFT, textColor=TEXT_PRIMARY,
    leftIndent=16, firstLineIndent=0, spaceBefore=0, spaceAfter=6)
kicker_style = ParagraphStyle(
    "Kicker", fontName="FreeSerif", fontSize=9, leading=12,
    textColor=TEXT_MUTED, spaceBefore=0, spaceAfter=2)
caption_style = ParagraphStyle(
    "Caption", fontName="FreeSerif", fontSize=8.5, leading=12,
    alignment=TA_CENTER, textColor=TEXT_MUTED, spaceBefore=3, spaceAfter=6)
th_style = ParagraphStyle(
    "TH", fontName="FreeSerif", fontSize=9.5, leading=13,
    textColor=colors.white, alignment=TA_LEFT)
td_style = ParagraphStyle(
    "TD", fontName="FreeSerif", fontSize=9.5, leading=13.5,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT)
td_bold_style = ParagraphStyle(
    "TDB", fontName="FreeSerif", fontSize=9.5, leading=13.5,
    textColor=HEADER_FILL, alignment=TA_LEFT)
stat_style = ParagraphStyle(
    "StatBig", fontName="FreeSerif", fontSize=21, leading=24,
    textColor=ACCENT, alignment=TA_CENTER)
stat_label_style = ParagraphStyle(
    "StatLabel", fontName="FreeSerif", fontSize=8.5, leading=11.5,
    textColor=TEXT_MUTED, alignment=TA_CENTER)
step_style = ParagraphStyle(
    "Step", fontName="FreeSerif", fontSize=10.5, leading=16.5,
    alignment=TA_LEFT, textColor=TEXT_PRIMARY,
    leftIndent=18, spaceBefore=0, spaceAfter=5)


def safe_keep_together(elements):
    total_h = 0
    for el in elements:
        _, h = el.wrap(AVAIL_W, PAGE_H)
        total_h += h
    if total_h <= MAX_KEEP_HEIGHT:
        return [KeepTogether(elements)]
    if len(elements) >= 2:
        return [KeepTogether(elements[:2])] + list(elements[2:])
    return list(elements)


def h1(num, text):
    """Numbered section heading with accent underline rule."""
    label = f"{num}.  {text}"
    para = Paragraph(f"<b>{label}</b>", h1_style)
    rule = HRFlowable(width="100%", thickness=1.2, color=ACCENT,
                      spaceBefore=2, spaceAfter=12)
    return [CondPageBreak(H1_ORPHAN), KeepTogether([para, rule])]


def stat_row(items):
    """Row of metric callout boxes: items = [(big, label), ...]."""
    cells = [[ [Paragraph(f"<b>{big}</b>", stat_style),
                Paragraph(label, stat_label_style)] for big, label in items ]]
    n = len(items)
    col_w = [AVAIL_W / n] * n
    t = Table(cells, colWidths=col_w, hAlign="CENTER")
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), CARD_BG),
        ("BOX", (0, 0), (-1, -1), 0.9, BORDER),
        ("INNERGRID", (0, 0), (-1, -1), 0.9, BORDER),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 12),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ]))
    return t


def data_table(header, rows, ratios, bold_first_col=False):
    col_w = [r * AVAIL_W for r in ratios]
    assert abs(sum(col_w) - AVAIL_W) < 1.0, "table width must equal available width"
    data = [[Paragraph(f"<b>{h}</b>", th_style) for h in header]]
    for row in rows:
        cells = []
        for i, cell in enumerate(row):
            style = td_bold_style if (bold_first_col and i == 0) else td_style
            cells.append(Paragraph(cell, style))
        data.append(cells)
    t = Table(data, colWidths=col_w, hAlign="CENTER", repeatRows=1)
    style = [
        ("BACKGROUND", (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ("TEXTCOLOR", (0, 0), (-1, 0), TABLE_HEADER_TEXT),
        ("GRID", (0, 0), (-1, -1), 0.5, BORDER),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 7),
        ("RIGHTPADDING", (0, 0), (-1, -1), 7),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]
    for r in range(1, len(data)):
        bg = TABLE_ROW_ODD if r % 2 == 1 else TABLE_ROW_EVEN
        style.append(("BACKGROUND", (0, r), (-1, r), bg))
    t.setStyle(TableStyle(style))
    return t


def bullets(story, items):
    for it in items:
        story.append(Paragraph(f"•  {it}", bullet_style))


# ---------- Header / footer ----------
def on_page(canvas, doc):
    canvas.saveState()
    # Header: doc title (left, muted) + accent rule
    canvas.setFont("FreeSerif", 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, PAGE_H - 0.55 * inch, DOC_TITLE.upper())
    canvas.setStrokeColor(ACCENT)
    canvas.setLineWidth(1.2)
    canvas.line(MARGIN, PAGE_H - 0.62 * inch, PAGE_W - MARGIN, PAGE_H - 0.62 * inch)
    # Footer: author (left) + page number (right) + light rule above
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(MARGIN, 0.62 * inch, PAGE_W - MARGIN, 0.62 * inch)
    canvas.setFont("FreeSerif", 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, 0.45 * inch, "PM CONTROL TOWER  -  Version 1.0.0")
    canvas.drawRightString(PAGE_W - MARGIN, 0.45 * inch, str(doc.page))
    canvas.restoreState()


# ---------- Story ----------
story = []

# ===== 1. The Platform at a Glance =====
story += h1(1, "The Platform at a Glance")
story += safe_keep_together([
    Paragraph(
        "PM CONTROL TOWER is an enterprise Project, Program and Portfolio Management platform built "
        "for top organizations that need one authoritative view of delivery. It carries a single dataset "
        "down the full management chain - portfolio, program, project, WBS, schedule, earned value, "
        "governance and leadership reporting - so every number a leader sees is computed from the same "
        "live operational data that teams update daily. There is no parallel reporting spreadsheet to "
        "reconcile and no month-end scramble to assemble board material.", body_style),
])
story.append(Paragraph(
    "The platform is deliberately executive-first. Role-based views give leaders a control tower of "
    "portfolio health, exceptions and decisions, while delivery teams work in the same system on tasks, "
    "timesheets and risks - no duplicate tools, no status bureaucracy. Realtime events keep every open "
    "screen current, and every create, update and decision is written to an immutable audit trail that "
    "auditors can inspect without engineering support.", body_style))
story.append(Spacer(1, 8))
story.append(stat_row([
    ("104", "REST API routes"),
    ("57", "data models"),
    ("36", "role-based views"),
    ("8", "governance roles"),
]))
story.append(Spacer(1, 12))

# ===== 2. The Module Map =====
story += h1(2, "The Module Map")
story += safe_keep_together([
    Paragraph(
        "Functionality is organized into eight module groups that mirror how an enterprise actually "
        "delivers work. Investment decisions happen at the portfolio and program level; planning happens "
        "once per project and is protected by baselines; control is exercised through engines and "
        "registers rather than meetings; execution stays lightweight for team members; and intelligence "
        "turns everything into reporting. The table below is the fastest way to navigate a live demo - "
        "each group maps directly to a section of the sidebar navigation.", body_style),
])
story.append(Spacer(1, 6))
story.append(data_table(
    ["Module group", "Focus", "Representative views"],
    [
        ["Portfolio", "Investment and structure",
         "Portfolios, Programs, Projects, Dashboard"],
        ["Plan", "Scope and schedule",
         "Requirements, WBS, Schedule (CPM), Milestones, Baselines, Register"],
        ["Control", "Delivery assurance",
         "EVM, RAID, Financials, Gates, Governance, Changes, Health"],
        ["Execute", "Team operations",
         "Inbox, Timesheets, Planner, Resources"],
        ["Intelligence", "Reporting and insight",
         "Leadership Control Tower, Reports, Analytics, Assistant"],
        ["Connect", "Integrations and automation",
         "Integrations, Webhooks, Automations, Notifications"],
        ["Admin", "Platform administration",
         "Users, Roles, Audit, Templates, Settings"],
        ["Project Workspace", "Single-project depth",
         "Overview, Scope, Schedule, RAID, EVM, Financials, Gates, Changes, Health, Audit tabs"],
    ],
    [0.16, 0.24, 0.60], bold_first_col=True))
story.append(Paragraph("Table 1: The eight module groups and their representative views.", caption_style))
story.append(Spacer(1, 6))

# ===== 3. Leadership Reporting & Executive Control Tower =====
story += h1(3, "Leadership Reporting and the Executive Control Tower")
story += safe_keep_together([
    Paragraph(
        "The Leadership Control Tower is the platform's differentiator. It answers the questions "
        "executives actually ask - are we within budget, what changed since the last report, which "
        "decisions are blocking delivery - from live data, with a strict honesty policy: any project "
        "with significant data gaps is classified GREY and can never present itself as green. Status is "
        "never self-declared; it is computed, versioned and comparable over time.", body_style),
])
bullets(story, [
    "<b>Exception-first feed</b> - critical risks, overdue decisions and due-soon milestones surface "
    "before everything else, so a leader reads the tower top-down in priority order.",
    "<b>Traceable auto-insights</b> - every sentence is derived from a named fact in the system; where "
    "evidence is missing the platform states INSUFFICIENT DATA instead of guessing.",
    "<b>Nothing-missed validation</b> - a 16-check audit of reporting completeness runs on every "
    "leadership pack, flagging exactly what a leader has not been told.",
    "<b>What-Changed engine</b> - every new report diffs automatically against the previous snapshot, "
    "making movement between reporting cycles explicit.",
    "<b>30/60/90 outlook</b> - upcoming milestones, decisions and financial exposure across the next "
    "three planning horizons.",
])
story.append(Spacer(1, 4))
story.append(Paragraph(
    "Per-project Executive Status Reports follow a fixed leadership contract: a three-paragraph summary "
    "written from facts, a seven-dimension status assessment, and - most importantly - Leadership "
    "Actions in four fields: WHAT must be decided, WHO owns it, BY WHEN it is needed, and what happens "
    "IF NO DECISION is taken. Overdue decisions auto-escalate into critical action items on the next "
    "report run, so nothing stalls silently.", body_style))
story.append(Paragraph(
    "The one-click Leadership Pack assembles a complete, versioned board pack - control tower, "
    "exception feed, insights, and seventeen sub-reports spanning risks, issues, milestones, financials "
    "(with forecast trend against the previous snapshot), resources, schedule, dependencies, decisions, "
    "scope, deliverables, actions, quality and KPI realization. Packs are audited, scheduled "
    "(daily, weekly, monthly or quarterly) and comparable headline-to-headline; a dedicated Meeting "
    "Mode renders the pack as nine numbered sections for the leadership meeting itself.", body_style))
story.append(Spacer(1, 8))
story.append(stat_row([
    ("20", "sections per Leadership Pack"),
    ("17", "sub-reports, all computed"),
    ("16", "nothing-missed checks"),
]))
story.append(Spacer(1, 12))

# ===== 4. Decision Engines =====
story += h1(4, "Decision Engines - EVM, CPM, Health and Governance")
story += safe_keep_together([
    Paragraph(
        "Beneath the reporting layer, six deterministic engines do the analytical work that organizations "
        "usually perform by hand. They run server-side on every relevant change, which means earned value, "
        "critical paths and health scores are always current - not a month old. This is what makes the "
        "control tower trustworthy: the numbers are produced by the same engines a PM would use, just "
        "continuously and for every project at once.", body_style),
])
story.append(Spacer(1, 6))
story.append(data_table(
    ["Engine", "What it computes", "What leadership gets"],
    [
        ["CPM schedule", "ES/EF/LS/LF, float and critical path from live task dependencies",
         "True critical path and slip impact per project"],
        ["Earned Value", "PV, EV, AC, CPI, SPI, EAC and variance against baseline",
         "Objective cost and schedule health, forecast to completion"],
        ["Health scoring", "Weighted multi-factor RAG across scope, schedule, cost, risk and quality",
         "One honest color per project, with contributing factors"],
        ["Governance gates", "Criteria-based stage gates with decision records",
         "A defensible stage-decision history per project"],
        ["Timesheet cascade", "Submit, approve, reject, lock workflow feeding actuals",
         "Actual effort and cost without manual collection"],
        ["Portfolio rollup", "Program and portfolio aggregation of progress, spend and health",
         "Investment-level view that reconciles with every project"],
    ],
    [0.16, 0.44, 0.40], bold_first_col=True))
story.append(Paragraph("Table 2: The six decision engines and their executive outputs.", caption_style))
story.append(Spacer(1, 6))

# ===== 5. Security, Roles & Deployment =====
story += h1(5, "Security, Roles and Deployment")
story += safe_keep_together([
    Paragraph(
        "Security follows enterprise expectations: JWT authentication with bcrypt-hashed credentials, "
        "role-based access control across 32 permissions and 8 roles, rate limiting and schema validation "
        "on every API route, and a complete audit trail of who changed what and when. The 8 roles - "
        "EXECUTIVE, PMO_ADMIN, PORTFOLIO_MANAGER, PROGRAM_MANAGER, PROJECT_MANAGER, FINANCE, AUDITOR and "
        "TEAM_MEMBER - map to real organizational positions, and every view, report and API respects the "
        "matrix, down to 403s that auditors can verify.", body_style),
])
story.append(Paragraph(
    "Deployment is intentionally boring to operate. The reference path is Docker Compose - application "
    "plus realtime gateway plus an optional Caddy TLS edge - with the database on a persistent volume. "
    "Bare-metal Node and Bun paths, an offline dependency bundle for air-gapped environments, and a "
    "PostgreSQL upgrade route are all documented in the accompanying eleven-guide documentation suite, "
    "including backup, restore and runbook procedures.", body_style))
story.append(Spacer(1, 4))
story.append(data_table(
    ["Deployment path", "Best fit", "Notes"],
    [
        ["Docker Compose", "Standard enterprise rollout",
         "One command up; app + realtime + optional TLS profile; persistent volume for SQLite"],
        ["Bare metal (Node or Bun)", "Regulated hosts without containers",
         "PM2 ecosystem file, nginx reverse proxy config and setup script included"],
        ["Offline / air-gapped", "Defense, government, secure data centers",
         "Pre-built node_modules bundle with all native Linux x64 binaries; no internet needed"],
        ["Cloud with managed Postgres", "Scale-out or multi-region growth",
         "Prisma schema ports to PostgreSQL; documented migration path"],
    ],
    [0.20, 0.28, 0.52], bold_first_col=True))
story.append(Paragraph("Table 3: Supported deployment paths.", caption_style))
story.append(Spacer(1, 6))
story.append(Paragraph(
    "The shipped reference dataset models a top organization: two portfolios, three programs and six "
    "projects with CPM schedules, baselines, RAID registers, budgets, forecasts, governance gates, "
    "decisions, actions and KPIs, plus twelve demo accounts across every role - including "
    "ceo@pmct.io (executive) and pmo@pmct.io (platform administrator). Everything shown below is the "
    "live product, not a mock-up. A suggested five-step demo path for the live session:", body_style))
bullets(story, [
    "<b>1.</b>  Log in as ceo@pmct.io, open the Leadership Control Tower, read the exception feed.",
    "<b>2.</b>  Drill into a red portfolio row's Executive Status Report and Leadership Actions block.",
    "<b>3.</b>  Record the pending DEC-101 decision and watch the tower update and the exception clear.",
    "<b>4.</b>  As pmo@pmct.io, generate a Leadership Pack and open Meeting Mode - nine numbered sections.",
    "<b>5.</b>  Close the loop: liam@pmct.io files a timesheet, program@pmct.io approves - actuals hit EVM.",
])

# ---------- Build ----------
doc = SimpleDocTemplate(
    OUT, pagesize=A4,
    leftMargin=MARGIN, rightMargin=MARGIN,
    topMargin=MARGIN, bottomMargin=MARGIN,
    title=DOC_TITLE, author="Z.ai", creator="Z.ai",
    subject="Executive overview and demo companion for the PM Control Tower platform")
doc.build(story, onFirstPage=on_page, onLaterPages=on_page)
print(f"body built: {OUT}")
